version: '3.7'

services:
  api:
    build: .
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 --lifespan on
    ports:
      - 8001:8000

networks:
  default:
    external:
      # temporary solution to connect to elastic
      name: elasticsearch_network
